name: Python CI
on: [push, pull_request]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - spark-version: 3.5.4
            scala-version: 2.12.18
            python-version: 3.9.19
    runs-on: ubuntu-22.04
    env:
      # define Java options for both official sbt and sbt-extras
      JAVA_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
      JVM_OPTS:  -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
      SPARK_VERSION: ${{ matrix.spark-version }}
      SCALA_VERSION: ${{ matrix.scala-version }}
    steps:
    - uses: actions/checkout@v4
    - uses: olafurpg/setup-scala@v13
      with:
        java-version: "openjdk@1.11"
    - uses: actions/cache@v4
      with:
        path: |
          ~/.ivy2/cache
        key: sbt-ivy-cache-spark-${{ matrix.spark-version}}-scala-${{ matrix.scala-version }}
    - name: Assembly
      run: build/sbt -v ++${{ matrix.scala-version }} -Dspark.version=${{ matrix.spark-version }} "set test in assembly := {}" assembly
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install -r ./python/requirements.txt
        pip install pyspark==${{ matrix.spark-version }}
    - name: Test
      env:
        SPARK_DRIVER_MEMORY: "4g"
        SPARK_EXECUTOR_MEMORY: "4g"
        PYSPARK_SUBMIT_ARGS: "--conf spark.sql.adaptive.enabled=false --conf spark.sql.shuffle.partitions=10 --conf spark.graphframes.component.cache.enabled=false pyspark-shell"
      run: |
        export SPARK_HOME=$(python -c "import os; from importlib.util import find_spec; print(os.path.join(os.path.dirname(find_spec('pyspark').origin)))")
        # Create log4j.properties to reduce logging
        echo "log4j.rootCategory=ERROR,console" > $SPARK_HOME/conf/log4j.properties
        echo "log4j.appender.console=org.apache.log4j.ConsoleAppender" >> $SPARK_HOME/conf/log4j.properties
        echo "log4j.appender.console.layout=org.apache.log4j.PatternLayout" >> $SPARK_HOME/conf/log4j.properties
        ./python/run-tests.sh
